### ISSUE TITLE
error in test_file_count

### ISSUE THREAD

**Issue by stringertheory** [23andMe/seqseek#8]
I'm looking forward to learning more and using this package!

When running `download_build_38`, I get an error in the tests:

```======================================================================
ERROR: test_file_count (seqseek.tests.build_specific_tests.build_38_tests.TestBuild38)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/stringer/.virtualenvs/23andme/lib/python2.7/site-packages/seqseek/tests/build_specific_tests/build_38_tests.py", line 16, in test_file_count
    file_count = len(fnmatch.filter(os.listdir(TestBuild38.GRCH38_PATH), '*.fa'))
OSError: [Errno 2] No such file or directory: '/Users/stringer/.seqseek/homo_sapiens_GRCh38'

----------------------------------------------------------------------
Ran 31 tests in 0.019s

FAILED (errors=1)
```

**Comment by matstrand** [comment]
Thank you for reporting this! This is a bug with the integrity test that verifies that the sequence files are functioning with the package properly. It is a vestige of the directory structure that was used in older versions of the package. 

This will be fixed promptly but you should still be able to safely use the package as it appears from your output that the other 30 integrity tests succeeded. There's no need for you to re-download the sequence files at this time and you should be able to proceed with your work.

**Comment by matstrand** [comment]
This is now fixed in master and updated in PyPi. You may wish to pip install -U seqseek but there are no substantial changes beyond the deletion of the (now defunct) integrity test.

**Comment by stringertheory** [comment]
Thanks!
